// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANPfGHarZQ-O9AL43fiEmIOrz0XVPEQGk',
    appId: '1:746875831607:web:91f1bb9b4d1c44574f06b2',
    messagingSenderId: '746875831607',
    projectId: 'chat-app-practice-cca12',
    authDomain: 'chat-app-practice-cca12.firebaseapp.com',
    storageBucket: 'chat-app-practice-cca12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtKetp8jjW9kpSf5WI8sbIDdG1y6eqVQg',
    appId: '1:746875831607:android:28ae75d718b790a14f06b2',
    messagingSenderId: '746875831607',
    projectId: 'chat-app-practice-cca12',
    storageBucket: 'chat-app-practice-cca12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvOSe5aO-OOMTIB4-t7b69JEflV5z_33Q',
    appId: '1:746875831607:ios:26c6ee52b93c75b64f06b2',
    messagingSenderId: '746875831607',
    projectId: 'chat-app-practice-cca12',
    storageBucket: 'chat-app-practice-cca12.appspot.com',
    iosBundleId: 'com.example.chatPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvOSe5aO-OOMTIB4-t7b69JEflV5z_33Q',
    appId: '1:746875831607:ios:26c6ee52b93c75b64f06b2',
    messagingSenderId: '746875831607',
    projectId: 'chat-app-practice-cca12',
    storageBucket: 'chat-app-practice-cca12.appspot.com',
    iosBundleId: 'com.example.chatPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEA7mpK7hX4e0uz_J2C12G1uj-bsfF_ys',
    appId: '1:746875831607:web:7021f76581fee17b4f06b2',
    messagingSenderId: '746875831607',
    projectId: 'chat-app-practice-cca12',
    authDomain: 'chat-app-practice-cca12.firebaseapp.com',
    storageBucket: 'chat-app-practice-cca12.appspot.com',
  );
}
